name: ferry_generator2_end_to_end
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  gql: ^1.0.0
  gql_exec: ^1.1.0
  gql_tristate_value: ^1.0.0
  ferry_exec:
    path: ../ferry_exec

dev_dependencies:
  build_runner: ^2.0.2
  ferry_generator2:
    path: ../ferry_generator2
  ferry:
    path: ../ferry
  test: ^1.24.0

dependency_overrides:
  ferry_exec:
    path: ../ferry_exec
